In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Data/NHL_game_log_all.csv')

In [5]:
df.head()

,Rk,Date,G,Age,Tm,Location,Opp,Result,Goals,Assists,PTS,PIM,Player
0,1,1997-12-06,1,22,MDA,A,PIT,L,0,0,0,0,Antti Aalto
1,2,1997-12-10,2,22,MDA,H,PIT,L,0,0,0,0,Antti Aalto
2,3,1997-12-12,3,22,MDA,H,WSH,W,0,0,0,0,Antti Aalto
3,1,1998-10-10,1,23,MDA,A,WSH,L,0,0,0,0,Antti Aalto
4,2,1998-10-11,2,23,MDA,A,PHI,L,0,0,0,0,Antti Aalto

In [6]:
# Get Season for which game was played
df['Season'] = df.Date.apply(lambda x: f'{x[0:4]}-{str(int(x[0:4])+1)}' if int(x[5:7])>=7 else f'{str(int(x[0:4])-1)}-{x[0:4]}')

In [7]:
 # Fix team names where team named switched but same franchise
df['Tm'] = df.Tm.apply(lambda x: 'ANA' if x == 'MDA' else x)
df['Tm'] = df.Tm.apply(lambda x: 'CHI' if x == 'CBH' else x)
df['Tm'] = df.Tm.apply(lambda x: 'ARI' if x == 'PHX' else x)

In [8]:
df['Opp'] = df.Opp.apply(lambda x: 'ANA' if x == 'MDA' else x)
df['Opp'] = df.Opp.apply(lambda x: 'CHI' if x == 'CBH' else x)
df['Opp'] = df.Opp.apply(lambda x: 'ARI' if x == 'PHX' else x)

In [9]:
# Find Season number and career game number for each line

def player_season(row):
    global player_dict
    return player_dict[row.Player][row.Season]

player_game_count = dict()
def player_num_games(row):
    global player_game_count
    if row.Player in player_game_count:
        player_game_count[row.Player] += 1
    else:
        player_game_count[row.Player] = 1
    return player_game_count[row.Player]

player_dict = dict()
for player in df.Player.unique():
    print(f'\r{player}                           ',end='')
        
    player_dict[player] = dict()
    for season_num,season in enumerate(df[df.Player == player].Season.unique()):
        player_dict[player][season] = season_num+1

Andrei Zyuzin

In [10]:
df['Player_Season_Num'] = df.apply(player_season, axis = 1)

In [11]:
df['Career_Game_Num'] = df.apply(player_num_games, axis = 1)

In [12]:
# Check that above worked
df[df.Player == 'Jaromir Jagr']

,Rk,Date,G,Age,Tm,Location,Opp,Result,Goals,Assists,PTS,PIM,Player,Season,Player_Season_Num,Career_Game_Num
549027,1,1990-10-05,1,18,PIT,A,WSH,W,0,0,0,0,Jaromir Jagr,1990-1991,1,1
549028,2,1990-10-07,2,18,PIT,H,NJD,W,1,0,1,0,Jaromir Jagr,1990-1991,1,2
549029,3,1990-10-09,3,18,PIT,A,STL,L,0,0,0,0,Jaromir Jagr,1990-1991,1,3
549030,4,1990-10-11,4,18,PIT,A,CHI,L,0,0,0,0,Jaromir Jagr,1990-1991,1,4
549031,5,1990-10-13,5,18,PIT,A,NYI,W,1,0,1,0,Jaromir Jagr,1990-1991,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550755,18,2017-12-16,18,45,CGY,H,NSH,L,0,0,0,0,Jaromir Jagr,2017-2018,24,1729
550756,19,2017-12-17,19,45,CGY,A,VAN,W,0,0,0,2,Jaromir Jagr,2017-2018,24,1730
550757,20,2017-12-28,20,45,CGY,A,SJS,L-SO,0,0,0,2,Jaromir Jagr,2017-2018,24,1731
550758,21,2017-12-29,21,45,CGY,A,ANA,L,0,0,0,0,Jaromir Jagr,2017-2018,24,1732
550759,22,2017-12-31,22,45,CGY,H,CHI,W,0,0,0,2,Jaromir Jagr,2017-2018,24,1733

In [72]:
df.head()

,Rk,Date,G,Age,Tm,Location,Opp,Result,Goals,Assists,PTS,PIM,Player,Season,Player_Season_Num
0,1,1997-12-06,1,22,ANA,A,PIT,L,0,0,0,0,Antti Aalto,1997-1998,1
1,2,1997-12-10,2,22,ANA,H,PIT,L,0,0,0,0,Antti Aalto,1997-1998,1
2,3,1997-12-12,3,22,ANA,H,WSH,W,0,0,0,0,Antti Aalto,1997-1998,1
3,1,1998-10-10,1,23,ANA,A,WSH,L,0,0,0,0,Antti Aalto,1998-1999,2
4,2,1998-10-11,2,23,ANA,A,PHI,L,0,0,0,0,Antti Aalto,1998-1999,2

In [77]:
df.to_csv('NHL_game_log_all_cleaned.csv',index=False)